---
title: "Load FAA ASIAS AIDS Data"
author: "Randall Rickert"
date: "2024-06-08"
output: github_document
---

## Purpose

The purpose of this R package is the loading of the *Accident/Incident Data System (AIDS)* dataset maintained and published by the United States Federal Aviation Administration (FAA) for analysis in R. The result is a dplyr::tibble, a dataframe-like object type I chose because I am using the _tidyverse_ metapackage for a case study of general aviation accident/incident trends.

## Data Source

[The raw AIDS data](https://www.asias.faa.gov/apex/f?p=100:189:::NO), updated at the end of each calendar month, is hosted on the FAA's [*Aviation Safety Information Analysis and Sharing (ASIAS)* web site](https://www.asias.faa.gov/). This code was developed using the March 30, 2024 update, which was the latest available at the time of this writing.

The FAA distributes the data in a series of tab-delimited text files. Data file base names begin with `a` or `e`, followed by the year span represented in the file, in the format: `YYYY_YY`. For example, `a2020_25.txt` contains aviation accident/incident observations from the year 2020 through the year 2025 inclusively. The files beginning with `a` contain 179 serially-named columns. Brief descriptions of the columns are stored in a separate fixed-width text file: `Afilelayout.txt`. The files beginning with `e` contain two columns: a column of remarks and a column of unique keys corresponding to one of the 179 columns in the `a` files, making it easy to naturally join the `e` file remarks to the `a` file columns.

Accident/incident event dates span roughly a century, which is most of the history of motorized heavier-than-air aviation, but the data are quite sparse until 1973, which presumably marks a dramatic change in aviation record-keeping practices.

Observations after 2008 appear to be preliminary data, having the sort of empirical values that might be reported immediately following an event (e.g. date/time, location, fatality count, and aircraft registration number), but missing such information as might depend on the findings of an investigation (e.g. causes, remedies, and contributing factors).

While the observations spanning 1973 through 2008 are relatively more complete, the completion rates for indivitual columns vary from 0.0% (no value is available for any observation) to 100.0% (a value is available for every observation), or flip from one extreme to the other at some point in time. This is not surprising, considering how agencies, regulations, and technologies can change with time. Of the 180 columns in the dataset, I extracted the subset that I thought most likely to be useful for my case study.

## Factor Codes

The FAA distributes tables of codes used for factor data in a single word processor document: `aidcodes.docx`. This document's Lack of structure makes it difficult to extract the individual tables programmatically, so I extracted each table manually to its own tab-delimited text file.

I inferred the mapping of those code tables to the serially-named data columns containing encoded values by comparing the data column descriptions in `Afilelayout.txt` with the table descriptions in `aidcodes.docx`, but not all data columns appear in `Afilelayout.txt` with useful descriptions.

Some of the encoded columns have corresponding decoded columns, identified by descriptions in `Afilelayout.txt` ending with the word _text_, allowing me to verify my code-table-to-column mappings by checking the values I decoded against values from the corresponding decoded _text_ columns. However, not all encoded columns have corresponding _text_ columns, nor are the existing _text_ columns completely populated.

## Use

If you have the _devtools_ package installed, you can load this package directly from GitHub with: `devtools::install_github("rrickert/faa.aids")`

```{r load data, echo=TRUE, message=FALSE, warning=FALSE, error=TRUE}
# If a path to fresh data is not specified, load_aids() will read
# the AIDS data packaged with this library.
library(faa.aids)
data <- load_aids()

# Get a summary of the tibble
library(skimr)
skim(data)
```